# Generated by Django 5.1.2 on 2024-12-04 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('data_entry', 'Data Entry'), ('translation', 'Translation'), ('transcription', 'Transcription and Captioning'), ('graphics', 'Graphics'), ('writing', 'Writing and Editing'), ('web_dev', 'App and Web Development'), ('project_mgmt', 'IT Project Management'), ('testing', 'Software Testing'), ('virtual_assist', 'Virtual Assistance'), ('social_media', 'Social Media Management'), ('ai_training', 'AI Model Training')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('max_freelancers', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_notes', models.TextField(blank=True, help_text='Common notes applicable to all responses')),
                ('extra_data', models.JSONField(blank=True, help_text='Category-specific data', null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'user')},
            },
        ),
    ]
