# Generated by Django 5.1.2 on 2026-01-10 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='selected_freelancer',
        ),
        migrations.AddField(
            model_name='job',
            name='selected_freelancers',
            field=models.ManyToManyField(blank=True, related_name='selected_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
