# Generated by Django 5.1.2 on 2025-06-08 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_chats', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='freelancer_chats', to='accounts.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('job', 'client', 'freelancer')},
        ),
    ]
