# Generated by Django 5.1.2 on 2026-01-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_mobile_money_provider_and_more'),
        ('core', '0002_remove_job_selected_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='accounts.profile'),
        ),
    ]
