# Generated by Django 5.1.2 on 2025-05-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
