# Generated by Django 5.1.2 on 2026-01-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_mobile_money_provider_and_more'),
        ('core', '0003_alter_job_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='accounts.profile'),
        ),
    ]
