# Generated by Django 5.1.2 on 2025-06-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_chat_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Review'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
