# Generated by Django 5.1.2 on 2025-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_slug_response_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
