# Generated by Django 5.0.3 on 2024-04-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_pay_id_no_alter_profile_pay_id'),
        ('core', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.profile'),
        ),
    ]
