# Generated by Django 5.1.2 on 2025-06-07 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0006_chat_active_chat_chat_uuid_delete_jobassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_chats', to='accounts.profile'),
        ),
    ]
