# Generated by Django 5.1.2 on 2025-06-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0007_alter_chat_active_alter_chat_chat_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_chats', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='freelancer_chats', to='accounts.profile'),
        ),
    ]
