# Generated by Django 5.1.2 on 2025-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
