# Generated by Django 5.0.4 on 2024-05-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='device_used',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='job',
            name='password',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='job',
            name='security_answer',
        ),
        migrations.AddField(
            model_name='job',
            name='max_freelancers',
            field=models.IntegerField(default=1),
        ),
    ]
