# Generated by Django 5.1.2 on 2025-06-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0008_alter_chat_client_alter_chat_freelancer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('job', 'client', 'freelancer')},
        ),
    ]
