# Generated by Django 5.1.2 on 2025-02-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_messageattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAttempt',
        ),
    ]
