# Generated by Django 5.1.2 on 2025-06-28 08:05

from django.db import migrations
from django.utils import timezone
import datetime


def fix_posted_date(apps, schema_editor):
    Job = apps.get_model('core', 'Job')
    for job in Job.objects.all():
        if job.posted_date is None:
            job.posted_date = timezone.now()
            job.save()
        elif not isinstance(job.posted_date, datetime.datetime):
            try:
                job.posted_date = datetime.datetime.combine(
                    job.posted_date, datetime.time(0, 0), tzinfo=timezone.get_current_timezone())
                job.save()
            except Exception as e:
                print(f"Failed to fix Job {job.id}: {e}")


class Migration(migrations.Migration):
    dependencies = [
        # Updated dependency
        ('core', '0008_alter_job_deadline_date_alter_job_posted_date'),
    ]
    operations = [
        migrations.RunPython(fix_posted_date),
    ]
