# Generated by Django 5.1.2 on 2025-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_jobattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preferred_freelancer_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=50),
        ),
    ]
