# Generated by Django 5.1.2 on 2025-06-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat_active_chat_chat_uuid_alter_chat_client_and_more'),
        ('core', '0009_alter_chat_unique_together'),
    ]

    operations = [
    ]
