# Generated by Django 5.1.2 on 2025-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250628_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for image files', null=True, upload_to='thumbnails/'),
        ),
    ]
