# Generated by Django 5.0.4 on 2024-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_job_device_used_remove_job_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
