# Generated by Django 5.0.4 on 2024-05-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_response_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='is_done',
        ),
    ]
