# Generated by Django 5.1.2 on 2025-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_email_verified'),
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(related_name='required_skills', to='accounts.skill'),
        ),
    ]
