# Generated by Django 5.0.4 on 2024-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_response_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_freelancers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
