# Generated by Django 5.1.2 on 2025-07-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_skills_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('data_entry', 'Data Entry'), ('translation', 'Translation'), ('transcription', 'Transcription and Captioning'), ('graphics', 'Graphics & Design'), ('writing', 'Writing and Editing'), ('web_dev', 'Web and App Development'), ('project_mgmt', 'IT Project Management'), ('testing', 'Software Testing'), ('virtual_assist', 'Virtual Assistance'), ('social_media', 'Social Media Management'), ('ai_training', 'AI Model Training'), ('seo', 'SEO and SEM'), ('content_creation', 'Content Creation'), ('video_editing', 'Video Editing'), ('photo_editing', 'Photo Editing'), ('customer_support', 'Customer Support'), ('sales', 'Sales and Lead Generation'), ('marketing', 'Digital Marketing'), ('cybersecurity', 'Cybersecurity'), ('qa', 'Quality Assurance'), ('cloud_services', 'Cloud Services'), ('blockchain', 'Blockchain Development'), ('devops', 'DevOps'), ('database_admin', 'Database Administration'), ('finance', 'Finance and Accounting'), ('legal', 'Legal Services'), ('hr', 'Human Resources'), ('training', 'Corporate Training'), ('game_dev', 'Game Development'), ('mobile_dev', 'Mobile App Development'), ('animation', '2D/3D Animation'), ('voice_over', 'Voice Over'), ('research', 'Research and Analysis'), ('data_science', 'Data Science & Analytics'), ('ai_dev', 'AI & Machine Learning Development'), ('network_admin', 'Network Administration'), ('system_admin', 'System Administration'), ('ecommerce', 'E-commerce Management'), ('product_mgmt', 'Product Management'), ('business_consulting', 'Business Consulting'), ('ux_ui', 'UX/UI Design'), ('scripting', 'Scripting and Automation'), ('tech_support', 'Technical Support'), ('procurement', 'Procurement and Logistics')], max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.jobcategory'),
        ),
    ]
