# Generated by Django 5.0.4 on 2024-05-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_pay_id_no_alter_profile_pay_id'),
        ('core', '0012_job_completed_freelancers_response_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='completed_freelancers',
        ),
        migrations.RemoveField(
            model_name='response',
            name='accepted',
        ),
        migrations.CreateModel(
            name='JobAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
    ]
