# Generated by Django 5.1.2 on 2024-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_job_completed_freelancers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('data_entry', 'Data Entry'), ('translation', 'Translation'), ('transcription', 'Transcription and Captioning'), ('graphics', 'Graphics'), ('writing', 'Writing and Editing'), ('web_dev', 'App and Web Development'), ('project_mgmt', 'IT Project Management'), ('testing', 'Software Testing'), ('virtual_assist', 'Virtual Assistance'), ('social_media', 'Social Media Management'), ('ai_training', 'AI Model Training')], default='data_entry', max_length=20),
        ),
    ]
