# Generated by Django 5.1.2 on 2025-07-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_job_required_freelancers_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_freelancers',
            field=models.IntegerField(default=1, help_text='Total number of applications to receive'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_freelancers',
            field=models.PositiveSmallIntegerField(default=1, help_text='If the job requires more than one freelancer'),
        ),
    ]
