# Generated by Django 5.1.2 on 2025-07-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_job_max_freelancers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='responses/cover_letters/'),
        ),
        migrations.AddField(
            model_name='response',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='responses/cvs/'),
        ),
        migrations.AddField(
            model_name='response',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='responses/portfolios/'),
        ),
    ]
