# Generated by Django 5.1.2 on 2025-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_response_cover_letter_response_cv_response_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='submitted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_freelancers',
            field=models.IntegerField(default=50, help_text='Set total number of applications to receive'),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_freelancer_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=50),
        ),
    ]
