# Generated by Django 5.1.2 on 2025-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_response_status_alter_job_max_freelancers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
