# Generated by Django 5.1.2 on 2025-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_response_marked_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reviewed_responses',
            field=models.ManyToManyField(blank=True, related_name='marked_jobs', to='core.response'),
        ),
    ]
