# Generated by Django 5.1.2 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_freelancers',
            field=models.IntegerField(default=1, help_text='Set total number of applications to receive'),
        ),
    ]
