# Generated by Django 5.1.2 on 2025-08-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_job_max_freelancers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When a freelancer was assigned', null=True),
        ),
    ]
