# Generated by Django 5.1.2 on 2025-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_job_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
