# Generated by Django 5.1.2 on 2025-09-16 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_response_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='cover_letter_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='cover_letter_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='cv_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='cv_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='portfolio_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='portfolio_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='portfolio_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for portfolio images', null=True, upload_to='responses/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='response',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='responses/cover_letters/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='responses/cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='responses/portfolios/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
        migrations.CreateModel(
            name='ResponseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='responses/sample_work/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'zip'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.response')),
            ],
        ),
    ]
