# Generated by Django 5.1.2 on 2025-09-16 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_messageattachment_file_alter_response_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='chat_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for image files', null=True, upload_to='chat_attachments/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='response',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='response_attachments/cover_letters/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='response_attachments/cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='response_attachments/portfolios/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='response',
            name='portfolio_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail for portfolio images', null=True, upload_to='response_attachments/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='responseattachment',
            name='file',
            field=models.FileField(upload_to='response_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'zip'])]),
        ),
    ]
