# Generated by Django 5.1.2 on 2025-09-16 18:20

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_messageattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Auto-generated thumbnail for image files', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='response',
            name='cover_letter',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='response',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='response',
            name='portfolio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'zip'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='response',
            name='portfolio_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Auto-generated thumbnail for portfolio images', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='responseattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responseattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'zip'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='responseattachment',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
