# Generated by Django 5.1.2 on 2025-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('new_freelancers', models.IntegerField(default=0)),
                ('new_clients', models.IntegerField(default=0)),
                ('new_jobs', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
                ('new_hires', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payouts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_bf58fd_idx')],
            },
        ),
    ]
