# Generated by Django 5.1.2 on 2025-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
    ]
