# Generated by Django 5.1.2 on 2025-11-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0002_dailyanalytics_total_users'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeographicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('user_count', models.IntegerField(default=0)),
                ('freelancer_count', models.IntegerField(default=0)),
                ('client_count', models.IntegerField(default=0)),
                ('job_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'location'],
                'indexes': [models.Index(fields=['date', 'location'], name='analytics_g_date_6dc888_idx')],
                'unique_together': {('date', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('successful_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'payment_method'],
                'indexes': [models.Index(fields=['date', 'payment_method'], name='analytics_p_date_b42717_idx')],
                'unique_together': {('date', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='CategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('completion_count', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcategory')),
            ],
            options={
                'ordering': ['-date', '-job_count'],
                'indexes': [models.Index(fields=['date', 'category'], name='analytics_c_date_db9ffd_idx')],
                'unique_together': {('date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SkillsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand_count', models.IntegerField(default=0)),
                ('supply_count', models.IntegerField(default=0)),
                ('avg_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
            ],
            options={
                'ordering': ['-date', '-demand_count'],
                'indexes': [models.Index(fields=['date', 'skill'], name='analytics_s_date_57ec84_idx')],
                'unique_together': {('date', 'skill')},
            },
        ),
    ]
