# Generated by Django 5.0.3 on 2025-12-02 12:44

from django.db import migrations

def create_schedule(apps, schema_editor):
    """
    Creates a Django-Q schedule to run the daily analytics update task.
    """
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.create(
        name='Daily Analytics Update',
        func='analytics.tasks.run_daily_analytics_update',
        schedule_type='D',  # Use 'D' for DAILY
        repeats=-1,  # Repeat indefinitely
    )

def remove_schedule(apps, schema_editor):
    """
    Removes the scheduled task.
    """
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.filter(name='Daily Analytics Update').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_comprehensiveanalytics_geographicanalytics_and_more'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.RunPython(create_schedule, reverse_code=remove_schedule),
    ]