# Generated by Django 5.1.2 on 2025-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
