# Generated by Django 5.0.3 on 2024-04-02 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='line_items',
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoicemgmt.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
