# Generated by Django 5.1.2 on 2025-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
