# Generated by Django 5.1.2 on 2025-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0002_invoice_slug_invoicelineitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
