# Generated by Django 5.1.2 on 2024-11-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0003_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
