# Generated by Django 5.1.2 on 2025-04-21 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('english', 'English'), ('swahili', 'Swahili'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('mandarin', 'Mandarin Chinese'), ('cantonese', 'Cantonese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('hindi', 'Hindi'), ('bengali', 'Bengali'), ('urdu', 'Urdu'), ('swahili', 'Swahili'), ('dutch', 'Dutch'), ('swedish', 'Swedish'), ('norwegian', 'Norwegian'), ('danish', 'Danish'), ('finnish', 'Finnish'), ('polish', 'Polish'), ('turkish', 'Turkish'), ('hebrew', 'Hebrew'), ('greek', 'Greek'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indonesian', 'Indonesian'), ('malay', 'Malay'), ('tagalog', 'Filipino/Tagalog'), ('czech', 'Czech'), ('slovak', 'Slovak'), ('hungarian', 'Hungarian'), ('romanian', 'Romanian'), ('bulgarian', 'Bulgarian'), ('ukrainian', 'Ukrainian'), ('farsi', 'Farsi/Persian'), ('afrikaans', 'Afrikaans'), ('amharic', 'Amharic'), ('other', 'Other')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('django', 'Django'), ('flask', 'Flask'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('spring', 'Spring Boot'), ('laravel', 'Laravel'), ('aspnet', 'ASP.NET'), ('jquery', 'jQuery'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind CSS'), ('android', 'Android Development'), ('ios', 'iOS Development'), ('flutter', 'Flutter'), ('reactnative', 'React Native'), ('xamarin', 'Xamarin'), ('sql', 'SQL'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('oracle', 'Oracle'), ('firebase', 'Firebase'), ('redis', 'Redis'), ('aws', 'AWS'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('jenkins', 'Jenkins'), ('gitops', 'GitOps'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('python_data', 'Python for Data Science'), ('r', 'R Programming'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('scikit', 'Scikit-Learn'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('uiux', 'UI/UX Design'), ('graphic_design', 'Graphic Design'), ('figma', 'Figma'), ('adobe_xd', 'Adobe XD'), ('sketch', 'Sketch'), ('photoshop', 'Adobe Photoshop'), ('illustrator', 'Adobe Illustrator'), ('agile', 'Agile Methodology'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('jira', 'Jira'), ('confluence', 'Confluence'), ('trello', 'Trello'), ('asana', 'Asana'), ('git', 'Git'), ('testing', 'Software Testing'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('seo', 'SEO'), ('data_analysis', 'Data Analysis'), ('technical_writing', 'Technical Writing')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('pay_id', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Binance', 'Binance')], default='M-Pesa', max_length=20)),
                ('pay_id_no', models.CharField(default='', max_length=20)),
                ('id_card', models.CharField(blank=True, max_length=10)),
                ('user_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], default='freelancer', max_length=20)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'user_type')},
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('entertainment', 'Entertainment'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('legal', 'Legal Services'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('energy', 'Energy'), ('telecom', 'Telecommunications'), ('media', 'Media'), ('other', 'Other')], max_length=100)),
                ('project_budget', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('preferred_freelancer_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=50)),
                ('languages', models.ManyToManyField(blank=True, to='accounts.language')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only'), ('custom', 'Custom Schedule'), ('not_available', 'Not Available')], default='full_time', max_length=50)),
                ('languages', models.ManyToManyField(blank=True, to='accounts.language')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='accounts.profile')),
                ('skills', models.ManyToManyField(blank=True, to='accounts.skill')),
            ],
        ),
    ]
