# Generated by Django 5.1.2 on 2025-11-22 06:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 7–15 digits, optional leading +.', regex='^\\+?\\d{7,15}$')])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing Issue'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('honeypot', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_sent', models.BooleanField(default=False)),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Us Submission',
                'verbose_name_plural': 'Contact Us Submissions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='accounts_co_timesta_3a63cb_idx'), models.Index(fields=['email'], name='accounts_co_email_e338e0_idx'), models.Index(fields=['contact_type'], name='accounts_co_contact_4e367e_idx'), models.Index(fields=['priority'], name='accounts_co_priorit_dbc16a_idx'), models.Index(fields=['is_read'], name='accounts_co_is_read_02713a_idx')],
            },
        ),
    ]
