# Generated by Django 5.1.2 on 2025-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If false, the freelancer will be hidden from public listings.'),
        ),
    ]
