# Generated by Django 5.1.2 on 2025-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freelancerprofile_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
