# Generated by Django 5.1.2 on 2025-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_profile_availability_profile_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, choices=[('data_entry', 'Data Entry'), ('translation', 'Translation'), ('transcription', 'Transcription & Captioning'), ('graphics', 'Graphics'), ('writing_editing', 'Writing & Editing'), ('app_dev', 'App Development'), ('web_dev', 'Web Development'), ('it_pm', 'IT Project Management'), ('software_testing', 'Software Testing'), ('virtual_assistance', 'Virtual Assistance'), ('social_media', 'Social Media Management'), ('ai_training', 'AI Model Training')], max_length=200),
        ),
    ]
