# Generated by Django 5.0.3 on 2024-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='biolocation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='biolocation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
