# Generated by Django 5.1.2 on 2025-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_freelancerprofile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
