# Generated by Django 5.1.2 on 2025-02-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_skills_delete_skill_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.CharField(blank=True, choices=[('10', '$10/hr'), ('50', '$50/hr'), ('100', '$100/hr'), ('150', '$150/hr'), ('200', '$200/hr'), ('250', '$250/hr'), ('300', '$300/hr'), ('500', '$500/hr')], max_length=10),
        ),
    ]
