# Generated by Django 5.1.2 on 2025-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contactus_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='paystack_recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_id',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Binance', 'Binance'), ('Airtel Money', 'Airtel Money')], default='M-Pesa', max_length=20),
        ),
    ]
