# Generated by Django 5.0.3 on 2024-03-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
