# Generated by Django 5.1.2 on 2025-11-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_mobile_money_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money')], default='M-pesa', max_length=50, null=True),
        ),
    ]
