# Generated by Django 5.1.2 on 2025-02-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_skill_remove_profile_skills_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio_links',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_media_links',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
