# Generated by Django 5.1.2 on 2025-02-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_skills_remove_profile_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_used',
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('javascript', 'JavaScript'), ('react', 'React'), ('nodejs', 'Node.js'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('devops', 'DevOps'), ('uiux', 'UI/UX Design')], max_length=100)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(choices=[(0, '0-1 years'), (1, '1-2 years'), (2, '2-3 years'), (3, '3-5 years'), (5, '5+ years')], default=0)),
                ('hourly_rate', models.DecimalField(choices=[(10, '$10/hr'), (20, '$20/hr'), (30, '$30/hr'), (40, '$40/hr'), (50, '$50/hr'), (75, '$75/hr'), (100, '$100/hr')], decimal_places=2, default=10.0, max_digits=10)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('not_available', 'Not Available')], default='full_time', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='accounts.profile')),
            ],
        ),
    ]
