# Generated by Django 5.1.2 on 2025-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_mobile_money_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money')], default='M-Pesa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_id',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money')], default='M-Pesa', max_length=20),
        ),
    ]
