# Generated by Django 5.1.2 on 2025-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_mobile_money_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('MPESA', 'MPESA'), ('Airtel Money', 'Airtel Money')], default='MPESA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_id',
            field=models.CharField(choices=[('MPESA', 'MPESA'), ('Airtel Money', 'Airtel Money')], default='mpesa', max_length=20),
        ),
    ]
