# Generated by Django 5.1.2 on 2025-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_portfolioproject_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
