# Generated by Django 5.1.2 on 2025-02-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_language_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_freelancer',
        ),
    ]
