# Generated by Django 5.1.2 on 2025-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_portfolioproject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_website',
            field=models.URLField(blank=True, help_text='Enter URL in the format https://nilltechsolutions.com/', null=True),
        ),
    ]
