# Generated by Django 5.1.2 on 2025-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_is_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('entertainment', 'Entertainment'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('legal', 'Legal Services'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('energy', 'Energy'), ('telecom', 'Telecommunications'), ('media', 'Media'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only'), ('custom', 'Custom Schedule'), ('not_available', 'Not Available')], default='full_time', max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('mandarin', 'Mandarin Chinese'), ('cantonese', 'Cantonese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('hindi', 'Hindi'), ('bengali', 'Bengali'), ('urdu', 'Urdu'), ('swahili', 'Swahili'), ('dutch', 'Dutch'), ('swedish', 'Swedish'), ('norwegian', 'Norwegian'), ('danish', 'Danish'), ('finnish', 'Finnish'), ('polish', 'Polish'), ('turkish', 'Turkish'), ('hebrew', 'Hebrew'), ('greek', 'Greek'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indonesian', 'Indonesian'), ('malay', 'Malay'), ('tagalog', 'Filipino/Tagalog'), ('czech', 'Czech'), ('slovak', 'Slovak'), ('hungarian', 'Hungarian'), ('romanian', 'Romanian'), ('bulgarian', 'Bulgarian'), ('ukrainian', 'Ukrainian'), ('farsi', 'Farsi/Persian'), ('afrikaans', 'Afrikaans'), ('amharic', 'Amharic'), ('other', 'Other')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('django', 'Django'), ('flask', 'Flask'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('spring', 'Spring Boot'), ('laravel', 'Laravel'), ('aspnet', 'ASP.NET'), ('jquery', 'jQuery'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind CSS'), ('android', 'Android Development'), ('ios', 'iOS Development'), ('flutter', 'Flutter'), ('reactnative', 'React Native'), ('xamarin', 'Xamarin'), ('sql', 'SQL'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('oracle', 'Oracle'), ('firebase', 'Firebase'), ('redis', 'Redis'), ('aws', 'AWS'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('jenkins', 'Jenkins'), ('gitops', 'GitOps'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('python_data', 'Python for Data Science'), ('r', 'R Programming'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('scikit', 'Scikit-Learn'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('uiux', 'UI/UX Design'), ('graphic_design', 'Graphic Design'), ('figma', 'Figma'), ('adobe_xd', 'Adobe XD'), ('sketch', 'Sketch'), ('photoshop', 'Adobe Photoshop'), ('illustrator', 'Adobe Illustrator'), ('agile', 'Agile Methodology'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('jira', 'Jira'), ('confluence', 'Confluence'), ('trello', 'Trello'), ('asana', 'Asana'), ('git', 'Git'), ('testing', 'Software Testing'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('seo', 'SEO'), ('data_analysis', 'Data Analysis'), ('technical_writing', 'Technical Writing')], max_length=100, unique=True),
        ),
    ]
