# Generated by Django 5.1.2 on 2026-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_mobile_money_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('nextjs', 'Next.js'), ('django', 'Django'), ('flask', 'Flask'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('spring', 'Spring Boot'), ('laravel', 'Laravel'), ('aspnet', 'ASP.NET'), ('jquery', 'jQuery'), ('bootstrap', 'Bootstrap'), ('tailwind', 'Tailwind CSS'), ('android', 'Android Development'), ('ios', 'iOS Development'), ('flutter', 'Flutter'), ('reactnative', 'React Native'), ('xamarin', 'Xamarin'), ('sql', 'SQL'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('oracle', 'Oracle'), ('firebase', 'Firebase'), ('redis', 'Redis'), ('aws', 'AWS'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('jenkins', 'Jenkins'), ('gitops', 'GitOps'), ('terraform', 'Terraform'), ('ansible', 'Ansible'), ('python_data', 'Python for Data Science'), ('r', 'R Programming'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('scikit', 'Scikit-Learn'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision'), ('datacleaning', 'Data Cleaning'), ('uiux', 'UI/UX Design'), ('graphic_design', 'Graphic Design'), ('figma', 'Figma'), ('adobe_xd', 'Adobe XD'), ('sketch', 'Sketch'), ('photoshop', 'Adobe Photoshop'), ('illustrator', 'Adobe Illustrator'), ('agile', 'Agile Methodology'), ('scrum', 'Scrum'), ('kanban', 'Kanban'), ('jira', 'Jira'), ('confluence', 'Confluence'), ('trello', 'Trello'), ('asana', 'Asana'), ('git', 'Git'), ('testing', 'Software Testing'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('seo', 'SEO'), ('data_analysis', 'Data Analysis'), ('technical_writing', 'Technical Writing'), ('qa_testing', 'QA Testing'), ('ebay_seller_hub_navigation', 'Ebay Seler Hub Navigation'), ('inventory_tracking', 'Inventory Tracking'), ('product_research', 'Product Research'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets'), ('ai_training', 'AI Training'), ('other', 'Other')], max_length=100, unique=True),
        ),
    ]
