# Generated by Django 5.1.2 on 2025-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_clientprofile_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pay_id_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
