# Generated by Django 5.1.2 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_device_alter_clientprofile_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('english', 'English'), ('swahili', 'Swahili'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('mandarin', 'Mandarin Chinese'), ('cantonese', 'Cantonese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('hindi', 'Hindi'), ('bengali', 'Bengali'), ('urdu', 'Urdu'), ('swahili', 'Swahili'), ('dutch', 'Dutch'), ('swedish', 'Swedish'), ('norwegian', 'Norwegian'), ('danish', 'Danish'), ('finnish', 'Finnish'), ('polish', 'Polish'), ('turkish', 'Turkish'), ('hebrew', 'Hebrew'), ('greek', 'Greek'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('indonesian', 'Indonesian'), ('malay', 'Malay'), ('tagalog', 'Filipino/Tagalog'), ('czech', 'Czech'), ('slovak', 'Slovak'), ('hungarian', 'Hungarian'), ('romanian', 'Romanian'), ('bulgarian', 'Bulgarian'), ('ukrainian', 'Ukrainian'), ('farsi', 'Farsi/Persian'), ('afrikaans', 'Afrikaans'), ('amharic', 'Amharic'), ('other', 'Other')], max_length=100, unique=True),
        ),
    ]
