# Generated by Django 5.1.2 on 2025-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_pay_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pay_id_no',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
