# Generated by Django 5.0.3 on 2024-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay_id_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_id',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Binance', 'Binance')], default='M-Pesa', max_length=20),
        ),
    ]
