# Generated by Django 5.1.2 on 2025-09-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_pay_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pay_id_no',
        ),
    ]
