# Generated by Django 5.1.2 on 2025-05-27 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('job_picked', 'Job Picked'), ('payment_received', 'Payment Received')], default=None, max_length=20)),
                ('payment_type', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('paypal', 'PayPal')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='wallet_wall_user_id_308704_idx'), models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'), models.Index(fields=['transaction_type'], name='wallet_wall_transac_2c0a43_idx'), models.Index(fields=['timestamp'], name='wallet_wall_timesta_59b20e_idx')],
            },
        ),
    ]
