# Generated by Django 5.1.2 on 2025-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_completed_wallettransaction_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_amount', models.DecimalField(decimal_places=2, help_text='Platform fee in percentage', max_digits=5)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
