# Generated by Django 5.1.2 on 2025-11-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_paymentbatch_wallettransaction_batch_payoutlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee amount (gross * rate)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross amount for the job (before platform fee)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentbatch',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='wallet.paymentperiod'),
        ),
        migrations.AlterField(
            model_name='paymentbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Net amount payable to freelancer (gross_amount - fee_amount). Kept as 'amount' for compatibility.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='rate',
            field=models.ForeignKey(blank=True, help_text='Optional link to the Rate record used when this tx was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.rate'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
