# Generated by Django 5.1.2 on 2025-11-26 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_rate_options_wallettransaction_fee_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('job_picked', 'Job Picked'), ('payment_processing', 'Payment Processing'), ('payment_received', 'Payment Received')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paymentbatch',
            unique_together={('user', 'period', 'provider')},
        ),
    ]
