# Generated by Django 5.1.2 on 2025-08-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_job_max_freelancers'),
        ('wallet', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.job'),
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the payment period, e.g. 'August 2025 - Week 1'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Payment Period',
                'verbose_name_plural': 'Payment Periods',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_period',
            field=models.ForeignKey(blank=True, help_text='Payment period this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.paymentperiod'),
        ),
    ]
