# Generated by Django 5.1.2 on 2026-01-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_paymentbatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
