# Generated by Django 5.1.2 on 2026-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_paymentbatch_provider_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentbatch',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
