# Generated by Django 5.1.2 on 2026-01-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallettransaction_provider_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
