# Generated by Django 5.1.2 on 2026-01-20 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_client'),
        ('wallet', '0008_payoutlog_processed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('job', 'user', 'transaction_type'), name='unique_job_user_tx_type'),
        ),
    ]
