# Generated by Django 5.1.2 on 2026-01-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallettransaction_unique_job_user_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('late', 'Late'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
