# Generated by Django 5.1.2 on 2026-01-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_paymentbatch_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentbatch',
            unique_together=set(),
        ),
    ]
