# Generated by Django 5.1.2 on 2025-09-16 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_training_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='pdf_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
